{% set name = "napari" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abac206bafc2eee1fb5058b31fec0faaaf40fde85af96010b24a8632fbc4c874

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - napari = napari.__main__:main

requirements:
  build:
    - pep517
    - setuptools_scm
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6

    # dependencies matched to pip
    - appdirs >=1.4.4
    - cachey >=0.2.1
    - dask >=2.1.0
    - imageio >=2.5.0
    - importlib-metadata >=1.5.0  # not needed for py>37 but keeping for noarch
    - ipykernel >=5.2.0
    - ipython >=7.7.0
    - napari-plugin-engine >=0.1.5
    - napari-svg >=0.1.4
    - numpy >=1.16.0
    - numpydoc >=0.9.2
    - pillow
    - psutil >=5.0
    - pyopengl >=3.1.0
    - pyyaml >=5.1
    - qtconsole >=4.5.1
    - qtpy >=1.7.0
    - scipy >=1.2.0
    - tifffile >=2020.2.16
    - toolz >=0.10.0
    - typing_extensions
    - vispy >=0.6.4
    - wrapt >=1.11.1

    # additional dependencies for convenience in conda-forge
    - fsspec
    - pyqt
    - scikit-image
    - zarr

test:
  requires:
    - fsspec
    - pytest
    - pytest-faulthandler
    - pytest-qt
    - xarray
    - pandas
    - pooch
    - pytest-ordering
    - pytest-timeout
    - zarr
  imports:
    - napari
  commands:
    - setx QT_API "pyqt5"  # [win]
    - export QT_API=pyqt5  # [unix]
    - which napari
    #- DISPLAY=localhost:1.0 xvfb-run -a bash -c 'napari --info'
    #- pytest --pyargs napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python

  description: |
    a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari

extra:
  recipe-maintainers:
    - jni
    - sofroniewn
    - kne42
    - royerloic
    - AhmetCanSolak
    - tlambert03
