{% set name = "napari" %}
{% set version = "0.5.0" %}

package:
  name: napari-meta

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 668484825abf2afa3473e2a7f222b58beb761b1e4757e45f1f29cfe54a319fe4
  - url: https://raw.githubusercontent.com/napari/napari/v{{ version }}/resources/conda_menu_config.json
    folder: resources
    sha256: 3920b144d72e8af8fe0da3da679b2d39aa2d097c10a2c75a3b4e42ffcef17cac

build:
  number: 1

outputs:
  - name: napari
    version: {{ version }}
    build:
      noarch: python
      script: PIP_NO_INDEX=True PIP_NO_DEPENDENCIES=True PIP_NO_BUILD_ISOLATION=False PIP_IGNORE_INSTALLED=True PYTHONDONTWRITEBYTECODE=True {{ PREFIX }}/bin/python -m pip install . -vv
      entry_points:
        - napari = napari.__main__:main

    requirements:
      host:
        - python >=3.9
        - pip
        - setuptools >=69
        - setuptools_scm >=8
      run:
        - python >=3.9

        # dependencies matched to pyproject.toml
        - app-model >=0.2.5,<0.3.0a
        - appdirs >=1.4.4
        - cachey >=0.2.1
        - certifi >=2018.1.18
        # Do not depend on base "dask" package since it pulls
        # in the distributed dependency
        # conda-forge doesn't have the dask-array subpackage
        # so depend on cytoolz and numpy manually
        - dask-core >=2021.10.0
        - cytoolz >=0.11.0
        - imageio >=2.20,!=2.22.1
        - jsonschema >=3.2.0
        - lazy_loader >=0.2
        - magicgui >=0.7.0
        - napari-console >=0.0.9
        - napari-plugin-engine >=0.1.9
        - napari-svg >=0.1.8
        - npe2 >=0.7.6
        - numpy >=1.22.2
        - numpydoc >=0.9.2
        - pandas >=1.3.0
        - pillow >=9.0
        - pint >=0.17
        - psutil >=5.0
        - psygnal >=0.5.0
        - pydantic >=1.9.0
        - pygments >=2.6.0
        - pyopengl >=3.1.0
        - pyyaml >=5.1
        - qtpy >=1.10.0
        - scikit-image >=0.19.1
        - scipy >=1.5.4
        - superqt >=0.6.7
        - tifffile >=2022.4.8
        - toolz >=0.10.0
        - tqdm >=4.56.0
        - typing_extensions >=4.2.0
        - vispy >=0.14.1,<0.15.0a0
        - wrapt >=1.11.1

        # additional dependencies for convenience in conda-forge
        - fsspec
        - pooch >=1.3.0
        - zarr >=2.12.0

      run_constrained:
        - napari-plugin-manager >=0.1.0a2,<0.3.0a0
        - pyside2 >=5.13.2,!=5.15.0
        - pyside6 <6.5|>=6.7
        - pyqt >=5.12.3,!=5.15.0,<6.0a0|>=6.5,!=6.6.1
        # Nice for performance, but optional. Inclusion under discussion.
        # - py-triangle
        # - numba >=0.57.1  # https://github.com/napari/napari/pull/6467#issuecomment-1819038165

    test:
      requires:
        - pyqt
      # needed if pytest is uncommented below in 'commands'
      #   - hypothesis
      #   - pytest
      #   - pytest-faulthandler
      #   - pytest-qt
      #   - xarray
      #   - pandas
      #   - pytest-timeout
      imports:
        - napari
      commands:
        - setx QT_API "pyqt5"  # [win]
        - export QT_API=pyqt5  # [unix]
        - which napari
        - napari --info  # [not linux]
        - 'QT_DEBUG_PLUGINS=1 LIBGL_DEBUG=verbose xvfb-run --auto-servernum napari --info | grep -C99 "napari: ${PKG_VERSION}"'  # [linux]
        # - pytest --pyargs napari

    about:
      home: http://napari.org
      license: BSD-3-Clause AND MIT
      license_file:
        - LICENSE
        - napari/_vendor/darkdetect/LICENSE
        - napari/_vendor/qt_json_builder/LICENSE
      summary: a fast n-dimensional image viewer in Python
      description: a fast n-dimensional image viewer in Python
      doc_url: http://napari.org
      dev_url: https://github.com/napari/napari

  - name: napari-menu
    version: {{ version }}
    build:
      noarch: python
      script:
        - mkdir -p "${PREFIX}/Menu"
        - sed "s/__PKG_VERSION__/{{ PKG_VERSION }}/" "{{ SRC_DIR }}/resources/conda_menu_config.json" > "{{ PREFIX }}/Menu/napari-menu.json"
        - cp "{{ SRC_DIR }}/napari/resources/logo.png" "{{ PREFIX }}/Menu/napari.png"
        - cp "{{ SRC_DIR }}/napari/resources/icon.icns" "{{ PREFIX }}/Menu/napari.icns"
        - cp "{{ SRC_DIR }}/napari/resources/icon.ico" "{{ PREFIX }}/Menu/napari.ico"
    requirements:
      build:
        - sed     # [unix]
      run:
        - napari {{ version }}.*
    test:
      imports:
        - napari
      commands:
        - test -f ${CONDA_PREFIX}/Menu/napari-menu.json

    # app:
    #   entry: python -m napari
    #   icon: "{{ SRC_DIR|replace('\\', '/') }}/napari/resources/logo.png"
    #   summary: a fast n-dimensional image viewer in Python
    #   own_environment: True

    about:
      home: http://napari.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: provides menu icons for napari
      description: provides menu icons for napari
      doc_url: http://napari.org
      dev_url: https://github.com/napari/napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python
  description: a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari

extra:
  feedstock-name: napari
  recipe-maintainers:
    - jni
    - sofroniewn
    - kne42
    - royerloic
    - AhmetCanSolak
    - goanpeca
    - jaimergp
