{% set name = "napari" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e57b65d77f0f2e91c15054f58e1e1d90a81c70d21647b2a38eaa507bbaf7280a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - napari = napari.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy >=1.2.0
    - scikit-image
    - vispy >=0.6.4
    - dask >=2.1.0
    - cachey >=0.2.1
    - zarr
    - fsspec
    - imageio >=2.5.0
    - importlib-metadata >=1.5.0
    - ipykernel >=5.1.1
    - ipython >=7.7.0
    - jupyter_client
    - qtpy >=1.7.0
    - qtconsole >=4.5.1
    - IPython
    - backcall
    - pillow
    - pluggy
    - psutil >=5.0
    - pyopengl >=3.1.0
    - pyside2
    - pyyaml >=5.1
    - wrapt >=1.11.1
    - numpy >=1.10.0
    - numpydoc >=0.9.2
    - napari-plugin-engine >=0.1.5
    - napari-svg >=0.1.3
    - tifffile >=2020.2.16
    - toolz >=0.10.0


test:
  requires:
    - fsspec
    - pytest
    - pytest-faulthandler
    - pytest-qt
    - xarray
    - pandas
    - pooch
    - pytest-ordering
    - pytest-timeout
    - zarr
  imports:
    - napari
  commands:
    - setx QT_API "pyside2"  # [win]
    - export QT_API=pyside2  # [unix]
    - which napari
    #- DISPLAY=localhost:1.0 xvfb-run -a bash -c 'napari --info'
    #- pytest --pyargs napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python

  description: |
    a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari

extra:
  recipe-maintainers:
    - jni
    - sofroniewn
    - kne42
    - royerloic
    - AhmetCanSolak
