{% set name = "napari" %}
{% set version = "0.4.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54bb85c3afbf12d1333512aa0f7bdae0d652ddbe6bede1476fc6d0e89c1c87fb

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - napari = napari.__main__:main

requirements:
  build:
    - pep517
    - setuptools_scm
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7

    # dependencies matched to pip
    - appdirs >=1.4.4
    - cachey >=0.2.1
    - certifi >=2020.6.20
    - dask >=2.15.0,!=2.28.0
    - imageio >=2.5.0,!=2.11.0
    - importlib-metadata >=1.5.0  # not needed for py>37 but keeping for noarch
    - jsonschema >=3.2.0
    - magicgui >=0.3.3
    - napari-console >=0.0.4
    - napari-plugin-engine >=0.1.9
    - napari-svg >=0.1.4
    - npe2 >=0.1.1
    - numpy >=1.18.5
    - numpydoc >=0.9.2
    - pandas >=1.1.0
    - pillow !=7.1.0,!=7.1.1
    - pint >=0.17
    - psutil >=5.0
    - pyopengl >=3.1.0
    - pyyaml >=5.1
    - pydantic >=1.8.1
    - qtpy >=1.7.0
    - scipy >=1.4.0
    - superqt >=0.2.5
    - tifffile >=2020.2.16
    - typing_extensions
    - toolz >=0.10.0
    - tqdm >=4.56.0
    - vispy >=0.9.4
    - wrapt >=1.11.1

    # additional dependencies for convenience in conda-forge
    - fsspec
    - pyqt
    - scikit-image
    - zarr

test:
  requires:
    - hypothesis
    - fsspec
    - pytest
    - pytest-faulthandler
    - pytest-qt
    - xarray
    - pandas
    - pip
    - pooch
    - pytest-timeout
    - zarr
  imports:
    - napari
  commands:
    - pip list
    - pip check
    - setx QT_API "pyqt5"  # [win]
    - export QT_API=pyqt5  # [unix]
    - which napari
    #- DISPLAY=localhost:1.0 xvfb-run -a bash -c 'napari --info'
    #- pytest --pyargs napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python
  description: a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari

extra:
  recipe-maintainers:
    - jni
    - sofroniewn
    - kne42
    - royerloic
    - AhmetCanSolak
    - tlambert03
    - goanpeca
    - jaimergp
